apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-pv-deployment
spec:
  selector:
    matchLabels:
      app: task-pv-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      containers:
        - name: task-pv-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
