apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath: 
    path: "/mnt/config"
  storageClassName: cool-storage-class
