apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-custom-local-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-local-storage
  resources:
    requests:
      storage: 100Mi
